file_uploader/accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^login$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout$', auth_views.logout, name='logout')
]

file_uploader/file_uploader/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('upload_form.urls', namespace = 'upload_form')),
    url(r'^', include('accounts.urls', namespace = 'accounts')),
    url(r'', include('social_django.urls', namespace='social')),
]

file_uploader/upload_form/urls.py
from django.conf.urls import include, url
from upload_form import views
#from upload_form.input_file import input_view
from django.contrib import admin

urlpatterns = [
    url(r'^$', views.form, name = 'form'),
    url(r'^smart_input/$', views.input, name = 'input'),
    url(r'^complete/$', views.complete, name = 'complete'),
    url(r'^list/$', views.list, name = 'list'),
    url(r'^oneprediction/$', views.oneprediction, name = 'oneprediction'),
    url(r'^(?P<label_id>[0-9]+)/results/$', views.results, name = 'results'),
    url(r'^(?P<label_id>[0-9]+)/vote/$', views.vote, name = 'vote'),
    url(r'^smart_annotation/$', views.annotation, name = 'annotation'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
]

file_uploader/upload_form/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from PIL import Image
from django.template.context_processors import csrf
from django.conf import settings
from django.http import HttpResponseNotModified, HttpResponse, Http404, HttpResponseRedirect
from .models import Message
from upload_form.models import FileNameModel
from upload_form.models import Choice
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
import sys, os
import subprocess
import base64
import json
import xml.etree.ElementTree as ET
import pickle
from os import listdir, getcwd
from os.path import join
import glob
from PIL import Image
from PIL.ExifTags import TAGS
import cv2
import numpy as np
import shutil

Static_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/'
signboard_voc_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/signboard_VOC/'

#これはいらないかも
UPLOADE_DIR_bbox = os.path.dirname(os.path.abspath(__file__)) + '/static/mapillary/sapporo/bboxImages/'

JSONFILE = os.path.dirname(os.path.abspath(__file__)) + '/static/JSON/'
new_UPLOADE_DIR_image = os.path.dirname(os.path.abspath(__file__)) + '/static/signboard_VOC/JPEGImages_backup/'
new_UPLOADE_DIR_image_source = os.path.dirname(os.path.abspath(__file__)) + '/static/signboard_VOC/JPEGImages/'
new_UPLOADE_DIR_bbox = os.path.dirname(os.path.abspath(__file__)) + '/static/signboard_VOC/bboxImages/'
new_UPLOADE_DIR_prediction = os.path.dirname(os.path.abspath(__file__)) + '/static/signboard_VOC/prediction/'
new_UPLOADE_DIR_prediction_after = os.path.dirname(os.path.abspath(__file__)) + '/static/signboard_VOC/prediction_after/'
new_UPLOADE_DIR_label = os.path.dirname(os.path.abspath(__file__)) + '/static/signboard_VOC/Annotations/'

#trainfileにmaster以外の人がラベル付けしたデータを.txtで格納
#masterfileはmasterがラベル付けしたデータを.txtで格納
trainfile = os.path.dirname(os.path.abspath(__file__)) + '/static/data/others.txt'
masterfile = os.path.dirname(os.path.abspath(__file__)) + '/static/data/master.txt'

twoflag = True
filename = {}
filename[0] = {}
filename[1] = {}
filename[2] = {}
filename[3] = {}
bbox = {}
label_data = {}
dict_label_data = {}
my_dict = {}
my_dict['user'] = {}
my_dict["label"] = {}
my_dict["bboxfilename"] = []
my_dict["mapillary"] = {}
my_dict["imagedata"] = []
user_dict = {}
empty_list = []
classes = ["signboard"]

my_dict["prediction_name_img_src"] = []
my_dict["prediction_name_img_src_after"] = []


@csrf_exempt
@login_required
def form(request):
    global twoflag
    if twoflag is False:
        return render(request, 'upload_form/complete.html')
    twoflag = False
    file_list = os.listdir(new_UPLOADE_DIR_image)
    for file_name in file_list:
        root, ext = os.path.splitext(file_name)
        flag = False
        for f in file_list:
            root_1, ext_1 = os.path.splitext(f)
            for i in range(8):
                if root == root_1 + '_{}'.format(i):
                    flag = True
                    break
            if flag:
                break
        if flag:
            continue
        im = Image.open(new_UPLOADE_DIR_image + file_name)
        lon_10 = ''
        lat_10 = ''
        # Exif データを取得
        # 存在しなければそのまま終了 空の辞書を返す
        try:
            exif = im._getexif()
            exif_table = {}
            for tag_id, value in exif.items():
                tag = TAGS.get(tag_id, tag_id)
                exif_table[tag] = value
            try:
                # 経度
                lon = exif_table['GPSInfo'][4]
                # 緯度
                lat = exif_table['GPSInfo'][2]
                lon_10 = lon[0][0] / lon[0][1] + (lon[1][0] / lon[1][1] * 60 + lon[2][0] / lon[2][1]) / 3600
                lat_10 = lat[0][0] / lat[0][1] + (lat[1][0] / lat[1][1] * 60 + lat[2][0] / lat[2][1]) / 3600
            except KeyError:
                pass
        except AttributeError:
            pass
        if ext == '.jpeg' or ext == 'png':
            change_file_name = root + '.jpg'
            os.rename(signboard_voc_DIR + 'JPEGImages/' + file_name, signboard_voc_DIR + 'JPEGImages/' + change_file_name)
            os.rename(new_UPLOADE_DIR_image + file_name, new_UPLOADE_DIR_image + change_file_name)
            abs_name = new_UPLOADE_DIR_image + change_file_name
            prediction_name_img_src = '/static/signboard_VOC/prediction/' + change_file_name
            prediction_name_img_src_after = '/static/signboard_VOC/prediction_after/' + change_file_name
            if not my_dict["mapillary"].keys == prediction_name_img_src_after:

                if lon_10:
                    my_dict["mapillary"].update(
                        {prediction_name_img_src_after: {'geometry': {'coordinates': [lon_10, lat_10]}}})
                else:
                    my_dict["mapillary"].update({prediction_name_img_src_after: 0})

            prediction_name = new_UPLOADE_DIR_prediction + change_file_name
            prediction_name_after = new_UPLOADE_DIR_prediction_after + change_file_name
            # 以下各画像に対する処理を記載する
            # 画像の検出処理
            #検出処理については自分のディレクトリの配置によって変更してください。
            if not os.path.isfile(prediction_name_after):
              
                args = ['/volume/darknet/darknet', 'detector', 'test',
                        '/volume/darknet/cfg/ten_city_all_copy.data',
                        '/volume/darknet/cfg/onlysignboard_voc.cfg',
                        '/volume/file_uploader/upload_form/static/backup/ten_city_all_copy_ceres/ten_city_all_copy/onlysignboard_voc_final.weights',
                        '{}'.format(abs_name),
                        '-thresh 0.1']
                try:
                    res = subprocess.check_output(args)

                except subprocess.CalledProcessError as e:
                    res = e.output.decode("utf-8").split("\n")  # リストに文字列を格納
                
                shutil.copyfile('predictions.jpg', prediction_name_after)
        elif ext == '.jpg':
            abs_name = new_UPLOADE_DIR_image + file_name
            prediction_name_img_src = '/static/signboard_VOC/prediction/' + file_name
            prediction_name_img_src_after = '/static/signboard_VOC/prediction_after/' + file_name
            if not my_dict["mapillary"].keys == prediction_name_img_src_after:

                if lon_10:
                    my_dict["mapillary"].update(
                        {prediction_name_img_src_after: {'geometry': {'coordinates': [lon_10, lat_10]}}})
                else:
                    my_dict["mapillary"].update({prediction_name_img_src_after: 0})
            prediction_name = new_UPLOADE_DIR_prediction + file_name
            prediction_name_after = new_UPLOADE_DIR_prediction_after + file_name
            # 以下各画像に対する処理を記載する
            # 画像の検出処理
            if not os.path.isfile(prediction_name_after):
            
                args = ['/volume/darknet/darknet', 'detector', 'test',
                        '/volume/darknet/cfg/ten_city_all_copy.data',
                        '/volume/darknet/cfg/onlysignboard_voc.cfg',
                        '/volume/file_uploader/upload_form/static/backup/ten_city_all_copy_ceres/ten_city_all_copy/onlysignboard_voc_final.weights',
                        '{}'.format(abs_name),
                        '-thresh 0.1']
                try:
                    res = subprocess.check_output(args)


                except subprocess.CalledProcessError as e:
                    res = e.output.decode("utf-8").split("\n")  # リストに文字列を格納

                shutil.copyfile('predictions.jpg', prediction_name_after)
    twoflag = True
    return redirect('upload_form:list')


def input(request):
    global twoflag
    if twoflag is False:
        return render(request, 'upload_form/complete.html')
    twoflag = False
    label_data.clear()
    if request.method != 'POST':
        twoflag = True
        print("Method: GET. Returning base page")

        return render(request, 'upload_form/smart_input.html')
    if len(request.FILES) == 0:
        print("No images uploaded.")
        twoflag = True
        return render(request, 'upload_form/smart_input.html')

    file = request.FILES['myfile']

    path = os.path.join(new_UPLOADE_DIR_image, file.name)
    filename[0][request.user.id] = file.name
    filename[1][request.user.id] = path
    filename[2][request.user.id] = '/static/signboard_VOC/JPEGImages_backup/' + file.name
    filename[3][request.user.id] = new_UPLOADE_DIR_image_source + file.name
    im = Image.open(file)

    # Exif データを取得
    # 存在しなければそのまま終了 空の辞書を返す
    try:
        exif = im._getexif()
    except AttributeError:
        print('Not exif')
        twoflag = True
        return render(request, 'upload_form/smart_input.html')

    # タグIDそのままでは人が読めないのでデコードして
    # テーブルに格納する
    exif_table = {}
    for tag_id, value in exif.items():
        tag = TAGS.get(tag_id, tag_id)
        exif_table[tag] = value
    try:
        # 経度
        lon = exif_table['GPSInfo'][4]
        # 緯度
        lat = exif_table['GPSInfo'][2]
    except KeyError:
        print('Not GPSInfo')
        twoflag = True
        return render(request, 'upload_form/smart_input.html')
    lon_10 = lon[0][0] / lon[0][1] + (lon[1][0] / lon[1][1] * 60 + lon[2][0] / lon[2][1]) / 3600
    lat_10 = lat[0][0] / lat[0][1] + (lat[1][0] / lat[1][1] * 60 + lat[2][0] / lat[2][1]) / 3600


    root, ext = os.path.splitext(filename[0][request.user.id])
    if ext == '.jpeg' or ext == '.png' or ext == '.JPG' or ext == '.JPEG':

        change_file_name = root + '.jpg'


        filename[1][request.user.id] = signboard_voc_DIR + 'JPEGImages_backup/' + change_file_name
        filename[0][request.user.id] = change_file_name
        filename[2][request.user.id] = '/static/signboard_VOC/JPEGImages_backup/' + change_file_name
        filename[3][request.user.id] = new_UPLOADE_DIR_image_source + change_file_name

file_uploader/upload_form/templates/upload_form/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Smart Annotation</title>
</head>
<body>
<h1>少々お待ちください</h1>
<br>
<!--<a href={% url 'upload_form:list' %}>戻る</a>-->
<button type="button" onclick="history.go(-1)">戻る</button>
</body>
</html>

file_uploader/upload_form/templates/upload_form/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <title>Smart Annotation</title>
</head>
<body>
<h1>{{label.file_name}}</h1>
    {% for key,value in bbox.items %}
        {% for k,v in bboxfilename.items %}
        {% if key ==  k   %}
        <img src="/static/signboard_VOC/bboxImages/{{ key }}" style="max-height:500px"/>
        {% endif %}
            {% endfor %}
<form action="{% url 'upload_form:vote' label.id %}" method="post">
{% csrf_token %}
{% for choice in label.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
{% endfor %}
<input type="submit" value="Vote" />
</form>
</ul>

</body>
</html>

file_uploader/upload_form/templates/upload_form/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!--key=にgoogle map api keyを入力してください-->
    <script src="http://maps.google.com/maps/api/js?sensor=true&key="></script>
    <style>
        #map {
        width: 1200px;
        height: 600px;
    }
    #list
    {
        width: 100px;
  height: 100px;
  background-color: red;
  overflow: scroll;
    }</style>
    <meta charset="UTF-8">
    <title>Smart Annotation</title>
</head>
<body>
<b>注意事項：マウスダウンした時に看板と認識出来るものをラベル付けしてください。</b><br>
<b>Annotation回数</b><br>
{% for name,number in user.items %}

{{ name }}:{{ number }}
{% endfor %}
<br>
<a href={% url 'upload_form:input' %}>画像を追加</a>
<!--ここから地図を書きます。-->
<input type="button" id="sapporo" value="札幌" onclick="toSapporo()" />
<input type="button" id="sendai" value="仙台" onclick="toSendai()" />
<input type="button" id="tokyo" value="東京" onclick="toTokyo()" />
<input type="button" id="osaka" value="大阪" onclick="toOsaka()" />
<input type="button" id="hakata" value="博多" onclick="toHakata()" />
<input type="button" id="koube" value="神戸" onclick="toKoube()" />
<input type="button" id="saitama" value="埼玉" onclick="toSaitama()" />
<input type="button" id="shinyokohama" value="新横浜" onclick="toShinyokohama()" />
<input type="button" id="hiroshima" value="広島" onclick="toHiroshima()" />
<input type="button" id="kawasaki" value="川崎" onclick="toKawasaki()" />
<input type="button" id="shizuoka" value="静岡" onclick="toShizuoka()" />
<input type="button" id="fukushima" value="福島" onclick="toFukushima()" />
<input type="button" id="nara" value="奈良" onclick="toNara()" />
<input type="button" id="kyoto" value="京都" onclick="toKyoto()" />
<input type="button" onclick="map.setZoom(map.getZoom()+1);" value="＋" />
<input type="button" onclick="map.setZoom(map.getZoom()-1);" value="－" />
<div id="map"></div>
<!--<div id="list"></div>-->
<!--{% for name,obj in label.items %}
    <h1>{{ name }}</h1>
    <form action="{% url 'upload_form:vote' obj.id %}" method="post">
        {% csrf_token %}
        {% for choice in obj.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        {% endfor %}
        <input type="submit" value="Vote"/>
    </form>
    {% for b in bboxfilename %}

        {% if b ==  name %}
            <p><img src="/static/mapillary/sapporo/bboxImages/{{ b }}" style="max-height:500px"/></p>
        {% endif %}


    {% endfor %}
{% endfor %}-->



<script>
    var map = null;
    var infowindow = new google.maps.InfoWindow();

    function init() {

        //マップの初期状態を設定
        var option = {
            zoom: 5,
            center: new google.maps.LatLng(35.4093320,136.7566470),
            mapTypeId: google.maps.MapTypeId.ROADMAP,
            disableDefaultUI: true
        };

        // 吹き出しを閉じる処理
        map = new google.maps.Map(document.getElementById("map"), option);
        google.maps.event.addListener(map, "click", function () {
            infowindow.close();
        });

        // 任意の位置にマーカーを追加
        {% for key, value in mapillary.items %}
            {% if value %}
                {% if value.bboxfilename %}
                    {% if value.geometry %}
                        /*var point = new google.maps.LatLng({{ value.geometry.coordinates.1 }}, {{ value.geometry.coordinates.0 }});

                        var marker = create_maker_change(point, "info", "<img src='{{ value.bboxfilename }}' style=\"max-height:400px\" /><br><p><form id = 'imagedata' method = 'post' name = 'form'>{% csrf_token %}<input type='hidden' name='imagedata' value='{{ value.bboxfilename }}'><input type='hidden' name='directorydata' value='{{ key }}'><input type='submit' value='修正'></form></p>");
                        */
                    {% endif %}
                {% else %}
                    var point = new google.maps.LatLng({{ value.geometry.coordinates.1 }}, {{ value.geometry.coordinates.0 }});
                    /*document.getElementById("list").innerHTML+= "<img src='{{ key }}' style=\"height:416px;width:416px\" /><br><p><form id = 'imagedata' method = 'post' name = 'form'>{% csrf_token %}<input type='hidden' name='imagedata' value='{{ key }}'><input type='hidden' name='directorydata' value='{{ key }}'><input type='submit' value='修正'></form></p>"*/
                    var marker = create_maker(point, "info", "<img src='{{ key }}' style=\"height:416px;width:416px\" /><br><p><form id = 'imagedata' method = 'post' name = 'form'>{% csrf_token %}<input type='hidden' name='imagedata' value='{{ key }}'><input type='hidden' name='directorydata' value='{{ key }}'><input type='submit' value='修正'></form></p>");
                {% endif %}
            {% endif %}
        {% endfor %}
    }

    function create_maker(latlng, label, html) {
        // マーカーを生成
        var marker = new google.maps.Marker({position: latlng, map: map, title: label});
        // マーカーをマウスオーバーした時の処理
        google.maps.event.addListener(marker, "mouseover", function () {
            infowindow.setContent(html);
            infowindow.open(map, marker);
        });
    }

    function create_maker_change(latlng, label, html) {
        // マーカーを生成
        var marker = new google.maps.Marker({
            position: latlng, map: map, title: label, icon: {
                url: 'https://maps.google.com/mapfiles/ms/icons/blue-dot.png',
                scaledSize: new google.maps.Size(40, 40)
            },
            optimized: false
        });
        // マーカーをマウスオーバーした時の処理
        google.maps.event.addListener(marker, "mouseover", function () {
            infowindow.setContent(html);
            infowindow.open(map, marker);
        });
    }
    function toSapporo() {
  map.panTo(new google.maps.LatLng(43.068661,141.350755));
  map.setZoom( 11 ) ;
}

function toSendai() {
  map.panTo(new google.maps.LatLng(38.260132,140.882438));
  map.setZoom( 16 ) ;
}

function toTokyo() {
  map.panTo(new google.maps.LatLng(35.681167,139.767052));
  map.setZoom( 12 ) ;
}

function toOsaka() {
  map.panTo(new google.maps.LatLng(34.702485,135.495951));
  map.setZoom( 16 ) ;
}

function toHakata() {
  map.panTo(new google.maps.LatLng(33.590045,130.420611));
  map.setZoom( 16 ) ;
}

 function toSaitama() {
  map.panTo(new google.maps.LatLng(35.906355,139.623066));
  map.setZoom( 16 ) ;
}

function toKawasaki() {
  map.panTo(new google.maps.LatLng(35.531365,139.696889));
  map.setZoom( 16 ) ;
}

function toShinyokohama() {
  map.panTo(new google.maps.LatLng(35.506808,139.617577));
  map.setZoom( 16 ) ;
}

function toHiroshima() {
  map.panTo(new google.maps.LatLng(34.397790,132.475340));
  map.setZoom( 16 ) ;
}

function toKoube() {
  map.panTo(new google.maps.LatLng(34.679767,135.177993));
  map.setZoom( 16 ) ;
}

function toNara() {
  map.panTo(new google.maps.LatLng(34.680993,135.819531));
  map.setZoom( 16 ) ;
}

function toShizuoka() {
  map.panTo(new google.maps.LatLng(34.972187,138.388900));
  map.setZoom( 16 ) ;
}

function toFukushima() {
  map.panTo(new google.maps.LatLng(37.754209,140.459613));
  map.setZoom( 16 ) ;
}

function toKyoto() {
  map.panTo(new google.maps.LatLng(34.985849,135.758767));
  map.setZoom( 16 ) ;
}
    google.maps.event.addDomListener(window, "load", init);

</script>

</body>
</html>

file_uploader/upload_form/templates/upload_form/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Smart Annotation</title>
</head>
<body>
<h1>{{label.file_name}}</h1>

<ul>
{% for choice in label.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'upload_form:list'  %}">Vote again?</a>
</body>
</html>

file_uploader/upload_form/templates/upload_form/smart_input.html
<!doctype html>
<html>
    <head>
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <style>
            .thumb {
                max-width: 100%;
                height: auto;
            }
        </style>
        <meta name="viewport" content="content">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Smart Annotation</title>
    </head>
    <body>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" id="files" name="myfile">
            <input type="submit" value="アップロード">
            <button type="button" onclick="location.reload()">戻る</button>
        </form>
        <!--<p>

            <input type="button" value="Undo" id="backBtn">
            <input type="button" value="Redo" id="forwardBtn">
            <input type="button" value="label" id="label">
        </p>-->
        <p>
            <output id="list"></output>
        </p>
    </body>
    <script>
        var down = 0;
        var can_label = false;
        var touchstart = true;
        $('#label').click(function() {
            if (can_label) {
                can_label = false;
                document.getElementById("label").value = "label";
            } else {
                can_label = true;
                document.getElementById("label").value = "not label";
            }
        });

        function handleFileSelect(evt) {
            var files = evt.target.files;

            // FileList object

            // Loop through the FileList and render image files as thumbnails.
            for (var i = 0, f; f = files[i]; i++) {

                // Only process image files.
                if (!f.type.match('image.*')) {
                    continue;
                }

                var imageMemory = new Array(5);
                // キャンバスのイメージの保存用配列
                var flagMemory = 0;
                // 現在のキャンバスの番号
                $('#backBtn, #forwardBtn').attr('disabled', true);

                // キャンバスを生成して，2d描画を指定
                var myCanvas = document.createElement("canvas");
                var myContext = myCanvas.getContext('2d');

                // 読み込んだ画像がここに入る
                var myImage = new Image();

                var reader = new FileReader();

                // 最初のキャンバス状態を保存
                function saveImageDatafirst() {
                    // 現在の状態を保存
                    imageMemory[flagMemory] = myContext.getImageData(0, 0, myCanvas.width, myCanvas.height);

                }

                // Closure to capture the file information.
                reader.onload = function(event) {
                    myImage.onload = function() {
                        // 大きさの指定．あんまりスマートじゃないので要修正
                        var width = 360
                        var height = myImage.naturalHeight * width / myImage.naturalWidth;
                        //"100%";

                        // (4) Cnavasにサイズアトリビュートを設定する
                        myCanvas.setAttribute('width', width);
                        myCanvas.setAttribute('height', height);
                        // (5) 描画
                        myContext.drawImage(myImage, 0, 0, width, height);
                        saveImageDatafirst();
                        $('#files').hide();
                    }

                    // 読み込んだ画像をimageのソースに設定
                    myImage.src = event.target.result;

                    $('#label').click(function() {

                        // "このキャンバス"に対するイベントを定義

                        myCanvas.onclick = function(e) {
                            if (touchstart) {

                                if (can_label) {

                                    if (e.changedTouches) {
                                        startX = e.changedTouches[0].clientX;
                                    } else {
                                        startX = e.clientX;
                                    }

                                    if (e.changedTouches) {
                                        startY = e.changedTouches[0].clientY;
                                    } else {
                                        startY = e.clientY;
                                    }
                                    var rect = e.target.getBoundingClientRect();
                                    startabsoluteX = startX - rect.left;
                                    startabsoluteY = startY - rect.top;
                                    console.log(startX);
                                    console.log(startY);
                                    console.log(startabsoluteX);
                                    console.log(startabsoluteY);
                                    down = 1;
                                    console.log("detected touch start event");
                                    touchstart = false;

                                } else {}
                            } else {

                                if (can_label) {
                                    if (e.changedTouches) {
                                        endX = e.changedTouches[0].clientX;
                                    } else {
                                        endX = e.clientX;
                                    }

                                    if (e.changedTouches) {
                                        endY = e.changedTouches[0].clientY;
                                    } else {
                                        endY = e.clientY;
                                    }
                                    var rect = e.target.getBoundingClientRect();
                                    endabsoluteX = endX - rect.left;
                                    endabsoluteY = endY - rect.top;
                                    console.log(endX);
                                    console.log(endY);
                                    console.log(endabsoluteX);
                                    console.log(endabsoluteY);
                                    console.log("detected touch end event");
                                    draw(myCanvas, endabsoluteX, endabsoluteY);
                                    touchstart = true;
                                    down = 0;
                                    saveImageData();
                                } else {}
                            }
                        }

                        /*
                    // ドラッグ中のイベント
                    myCanvas.onmousemove = function(e) {
                        if (down == 1) {
                            var endX = e.pageX;
                            var endY = e.pageY;

                            console.log("detected mouse move event");
                            draw(myCanvas, endX, endY);
                        }
                    }

                    myCanvas.ontouchmove = function(e) {
                        if (down == 1) {
                            var endX = e.pageX;
                            var endY = e.pageY;

                            console.log("detected touch move event");
                            draw(myCanvas, endX, endY);
                        }
                    }
                    */

                    });

                    // 現在のキャンバス状態を保存
                    function saveImageData() {
                        // 現在の状態を保存
                        if (flagMemory == imageMemory.length - 1) {
                            imageMemory.shift();
                        } else {
                            ++flagMemory;
                        }

                        if (flagMemory == imageMemory.length - 1) {
                            $('#forwardBtn').attr('disabled', true);
                        }

                        imageMemory[flagMemory] = myContext.getImageData(0, 0, myCanvas.width, myCanvas.height);

                        $('#backBtn').attr('disabled', false);
                    }
                    // 戻るボタン
                    $('#backBtn').click(function() {
                        if (flagMemory > 0) {
                            flagMemory--;
                            myContext.putImageData(imageMemory[flagMemory], 0, 0);

                            $('#forwardBtn').attr('disabled', false);
                            if (flagMemory == 0) {
                                $('#backBtn').attr('disabled', true);
                            }
                        }
                    });
                    // 進むボタン
                    $('#forwardBtn').click(function() {
                        if (flagMemory < imageMemory.length - 1) {
                            flagMemory++;
                            myContext.putImageData(imageMemory[flagMemory], 0, 0);

                            $('#backBtn').attr('disabled', false);
                            if (flagMemory == imageMemory.length - 1) {
                                $('#forwardBtn').attr('disabled', true);
                            }
                        }

                    });

                    document.getElementById('list').insertBefore(myCanvas, null);
                    var br = document.createElement('br');
                    document.getElementById('list').insertBefore(br, myCanvas);
                }

                // Read in the image file as a data URL.
                reader.readAsDataURL(f);
            }
        }

        // 四角形を描きます
        function draw(targetCanvas, x, y) {
            var context = targetCanvas.getContext('2d');

            context.strokeStyle = '#FF0000';
            // 線の太さを指定
            context.lineWidth = 4;

            context.strokeRect(startabsoluteX, startabsoluteY, x - startabsoluteX, y - startabsoluteY);
            if (down == 1) {
                context.beginPath();

            }

        }

        document.getElementById('files').addEventListener('change', handleFileSelect, false);
    </script>
</html>