file_uploader/accounts/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views


app_name = 'accounts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^create$', views.create, name='create'),
    url(r'^login$', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^logout$', auth_views.logout, name='logout')
]

file_uploader/file_uploader/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('upload_form.urls', namespace = 'upload_form')),
    url(r'^', include('accounts.urls', namespace = 'accounts')),
    url(r'', include('social_django.urls', namespace='social')),
]

file_uploader/accounts/models.py
from django.db import models

# Create your models here.

file_uploader/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

@login_required
def index(request):
    return render(request, 'accounts/index.html')

def new(request):
    form = UserCreationForm()
    return render(request, 'accounts/new.html', {'form': form,})

def create(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('./login')
        return render(request, 'accounts/new.html', {'form': form,})
    else:
        raise Http404

file_uploader/accounts/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>accounts/index</p>
</body>
</html>

file_uploader/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url 'upload_form:accounts:login' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors.username }}
    {{ form.username }}
    {{ form.errors.password }}
    {{ form.password }}
    <input type="submit" value="Login">
    <br>Username &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Password
</form>
<!--<button type="button" onclick="location.href='{% url 'social:begin' 'twitter' %}'">Twitter</button>-->
<button type="button" onclick="location.href='{% url 'accounts:new' %}'">アカウント作成画面へ</button>
</body>
</html>

file_uploader/accounts/templates/accounts/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="{% url 'accounts:create' %}">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors.username }}
    {{ form.username }}
    {{ form.errors.password1 }}
    {{ form.password1 }}
    {{ form.errors.password2 }}
    {{ form.password2 }}
    {{ form.errors.email }}
    {{ form.email }}
    <input type="submit" value="Create">
    <br>Username &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Password &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Re-password
</form>
</body>
</html>